name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies and run tests
      working-directory: ./frontend
      run: |
        npm install
        npm test

    - name: Install backend dependencies and run tests
      working-directory: ./backend
      run: |
        npm install
        npm test

    - name: Build Docker images
      run: |
        docker build -t myapp/frontend:latest ./frontend
        docker build -t myapp/backend:latest ./backend

    - name: Push Docker images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push myapp/frontend:latest
        docker push myapp/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: myapp-task
        service: myapp-service
        cluster: myapp-cluster
        wait-for-service-stability: true
